# Generated by Django 3.2 on 2021-05-14 22:22

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.TextField(max_length=300)),
                ('interests', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), size=10)),
                ('profile_pic', models.ImageField(blank=True, default='media/defaultPicture.png', max_length=255, null=True, upload_to='userimg/')),
            ],
        ),
        migrations.RenameField(
            model_name='account',
            old_name='updated_at',
            new_name='updated',
        ),
        migrations.RemoveField(
            model_name='account',
            name='bio',
        ),
        migrations.RemoveField(
            model_name='account',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='account',
            name='id',
        ),
        migrations.RemoveField(
            model_name='account',
            name='interests',
        ),
        migrations.RemoveField(
            model_name='account',
            name='profile_pic',
        ),
        migrations.AddField(
            model_name='account',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='account',
            name='email',
            field=models.EmailField(max_length=50, unique=True, verbose_name='email'),
        ),
        migrations.AlterField(
            model_name='account',
            name='password',
            field=models.CharField(max_length=100),
        ),
        migrations.AddField(
            model_name='account',
            name='profile',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='accounts.profile'),
        ),
    ]
